# Generated by Django 5.2.3 on 2025-07-11 18:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0003_alter_requestform_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='bill',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
