# Generated by Django 5.2.3 on 2025-07-11 18:53

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0005_alter_requestform_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='bill',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='bills/'),
        ),
    ]
