# Generated by Django 5.2.3 on 2025-07-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0006_alter_requestform_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='bill',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
