# Generated by Django 5.2.3 on 2025-07-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0007_alter_requestform_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='bill',
            field=models.URLField(blank=True, null=True),
        ),
    ]
