# Generated by Django 5.2.3 on 2025-07-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0013_alter_requestform_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='bill',
        ),
        migrations.AddField(
            model_name='requestform',
            name='bill_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
